#redis配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 300000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jsd2107?useSSL=true&characterEncoding=utf-8&useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password: root


mybatis:
  type-aliases-package: com.entor.entity
  mapper-locations: classpath:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration.map-underscore-to-camel-case: true
server:
  port: 8090

